SVY-19181 Add support for generics in docgenerator
added check for
java.lang.NullPointerException: Cannot invoke
"String.lastIndexOf(String)" because "baseBinaryName" is null
	at com.servoy.eclipse.docgenerator.metamodel.TypeName.buildShortName(TypeName.java:438)
	at com.servoy.eclipse.docgenerator.metamodel.TypeName.<init>(TypeName.java:229)
	at com.servoy.eclipse.docgenerator.parser.ServoyPluginDetector.isServoyPlugin(ServoyPluginDetector.java:92)